import type { NextPage } from 'next'
import Head from 'next/head'
import { useMediaQuery } from 'react-responsive'
import GenerateQRCode from '../components/GenerateQRCode'
import LoginForm from '../components/LoginForm'
import Link from 'next/link'


const Home: NextPage = () => {
  const sessionId = "dadkjmnamkadkmk1123"

  const isMobile = useMediaQuery({ query: '(max-width:768px)' });

  return (
    <>
      <Head>
        <title>Login | Send Your Work</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex h-screen items-center justify-around overflow-visible relative">
        <img src="/Rectangle 103.svg" className="absolute z-0 left-24 w-1/3" />
        <img src="/Rectangle93.svg" className="absolute z-0 left-1/2 bottom-20" />
        <img src="/Rectangle94.svg" className="absolute z-0 right-52 w-20 top-20" />
        <img src="/Star 6.svg" alt="" className="absolute left-52 top-10" />
        <img src="/Half-circle.svg" alt="" className="absolute right-0 bottom-0 w-2/12" />
        <Link href="/">
          <img src="/close.svg" className="cursor-pointer absolute right-10 top-10" />
        </Link>
        <LoginForm />
        <div className="flex flex-col w-auto bg-white items-center justify-between h-2/5 rounded-xl myShadow">
          <h1 className="text-4xl font-bold m-5">Sign in with QR</h1>
          <GenerateQRCode text={sessionId} />
        </div>
      </div>
    </>
  )
}

export default Home
