import Head from 'next/head'
import Link from 'next/link'
import { useRef } from 'react'
import RegisterForm from '../components/RegisterForm'
import { useMediaQuery } from 'react-responsive'
import withoutAuth from '../components/withoutAuth'

export default withoutAuth(function Register(): JSX.Element {
    const photo = useRef<HTMLImageElement>(null)
    const isMobile = useMediaQuery({ query: '(max-width: 768px)' });
    return (
        <>
            <Head>
                <title>Login | Send Your Work</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className="flex h-screen items-center justify-around overflow-visible relative">
                {!isMobile && <img src="/Star 6.svg" className="absolute left-24 top-12" />}
                <img src="/Rectangle93.svg" className="absolute z-0 left-1/4 bottom-20" />
                <img src="/Rectangle 103.svg" className="absolute z-0  left-1/5 w-2/5" ref={photo} />
                <img src="/Rectangle94.svg" className="absolute z-0 right-52 w-20 top-14" />
                <img src="/Half-circle.svg" alt="" className="absolute right-0 bottom-0 w-2/12" />
                <RegisterForm />
                <Link href="/">
                    <img src="/close.svg" className="cursor-pointer absolute right-10 top-10" />
                </Link>
            </div>
        </>
    )
})