import Head from 'next/head'
import Link from 'next/link'
import RegisterForm from '../components/RegisterForm'

export default function Register(): JSX.Element {
    return (
        <>
            <Head>
                <title>Login | Send Your Work</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className="flex h-screen items-center justify-around overflow-visible relative">
                <RegisterForm />
                <Link href="/">
                    <img src="/close.svg" className="cursor-pointer absolute right-10 top-10" />
                </Link>
            </div>
        </>
    )
}